### PR TITLE
Compatibility updates

### LINKED ISSUE #3: ANSI Colors errors in Windows 10 version 10.0.14393 (Windows Anniversary Update)
More info: [https://gist.github.com/RDCH106/6562cc7136b30a5c59628501d87906f7](https://gist.github.com/RDCH106/6562cc7136b30a5c59628501d87906f7)

### PR DESCRIPTION
**Pull request by RDCH106**
Updates:

- Code ported to Python 3
- Fixed #3  ASCI color problem in Windows 10 console

### CODE REVIEW

**Comment by gardaud** [comment]
I'll be happy to merge the Windows fixes if they are in their own pull request.

Regarding python 3 compatibility, that'd be great to have, but considering the low complexity of the code, I'd rather have python2/python3 in the same file. If you issue a separate merge request that makes the source file bilingual, I'll be happy to merge it in as well.

**Comment by RDCH106** [comment]
I tried it as you say, but I did not get to implement it in Python 2 and Python 3 in the same file.

**Comment by RDCH106** [comment]
It is convenient to update the code to Python 3 because it is the present and future of Python. I did the Python 3 version and I kept the previous version with the fix to assure the backward compatibility.

**Comment by gardaud** [comment]
I agree that the code should run on Python 3, but it should be feasible to have a bilingual file. What issue(s) did you encounter when trying to support the 2 version in the same file?

**Comment by RDCH106** [comment]
The print function is the issue.

There no common way to print something without return in Python 2 and Python 3.

**Comment by gardaud** [comment]
What about using `__future__ import print_function`? 

Please issue a separate merge request for Windows color support, on the currently existing file.

I'll happily update the file to be python2/3 compatible when I have some time later.

**Comment by RDCH106** [comment]
I am going to do some tests with that.

**Comment by RDCH106** [comment]
Yes!! It works.

Previously I tried to use `__future__ import print_function` but with no result.

Ready to Merge!! ;-)

**Comment by gardaud** [comment]
Wonderful - thanks a lot for your contribution!

**Pull request merged**
